version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-manager-backend
    ports:
      - "3000:3000"
    env_file:
      - .env  # Charge automatiquement toutes vos variables d'environnement locales
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    container_name: account-manager-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password # Assurez-vous que cela correspond à votre DATABASE_URL dans le .env
      - MYSQL_DATABASE=account_manager
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data:
